Don't build on `darwin/arm` due to an IPv6 build issue.
```
--> darwin/arm error: exit status 2
Stderr: # github.com/hashicorp/serf/vendor/github.com/hashicorp/go.net/ipv6
vendor/github.com/hashicorp/go.net/ipv6/sys_darwin.go:15: undefined: syscall.IPV6_2292HOPLIMIT
vendor/github.com/hashicorp/go.net/ipv6/sys_darwin.go:16: undefined: syscall.IPV6_2292PKTINFO
vendor/github.com/hashicorp/go.net/ipv6/sys_darwin.go:17: undefined: syscall.IPV6_2292NEXTHOP
```